# Generated by Django 3.0.4 on 2020-04-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('profession', models.CharField(max_length=50, verbose_name='Профессия')),
                ('services', models.TextField(verbose_name='Услуги (цена);')),
                ('priority', models.IntegerField(verbose_name='Приоритет показа на странице')),
            ],
        ),
    ]
