# Generated by Django 3.0.4 on 2020-04-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20200401_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profession_en',
            field=models.CharField(default='Electric', max_length=50, verbose_name='Профессия на английском (для фото)'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatars'),
        ),
    ]
