# Generated by Django 3.0.4 on 2020-04-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20200402_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='profession_en',
        ),
    ]
