# Generated by Django 3.0.4 on 2020-04-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_agent_profession_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profession_description',
            field=models.CharField(default='Описание услуг', max_length=200, verbose_name='Мини описание услуг'),
        ),
    ]
