# Generated by Django 3.0.6 on 2020-05-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_profession_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='profession_description',
        ),
    ]
